# Evaluation

## What have I learned?
* How Colour Sensors work having a LED projecting the light to reflect off a surface
to see the reflected light intensity
* You can secure and improve your robot by framing the outside for extra support
* The best designs are usually stable and compact
* Make a shield that can fit against the Colour Sensors so that if you're using 
reflected light intensity there will be no interference from ambient light
* Ways to compare variable to other parameters or inputs to have a output of 
advanced things (Wall avoiding, etc)

## Code
Based off of the Wall Avoiding video I have created my own code for this agenda
and assume to test it. The eventuality might turn out bad though it's those steps
every coder has to take!
